# Generated by Django 3.1.3 on 2021-01-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210127_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('review', models.CharField(choices=[('1', 'One Star'), ('2', 'Two Stars'), ('3', 'Three Stars'), ('4', 'Four Stars'), ('5', 'Five Stars')], default='1', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='reviews',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='main_app.review'),
            preserve_default=False,
        ),
    ]
