# Generated by Django 3.1.3 on 2021-01-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210127_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', 'One Star'), ('2', 'Two Stars'), ('3', 'Three Stars'), ('4', 'Four Stars'), ('5', 'Five Stars')], default='1', max_length=1),
        ),
    ]
